### ISSUE TITLE
EPC QR codes in Rechnungen?

### ISSUE THREAD

**Issue by cybrwshl** [swablab/documents#4]
Hab mal kurz recherchiert: Wäre es nicht ein richtig nices Feature wenn unsere Rechnungen einen SEPA QR Code hätten?

```typ
#import "@preview/cades:0.3.0": qr-code

#qr-code("BCD\n001\n1\nSCT\nBPOTBEB1\nRed Cross of Belgium\nBE72000000001616\nEUR1\nCHAR\n\nUrgency fund\nSample EPC QR code\n", width: 2cm)
```

- https://en.wikipedia.org/wiki/EPC_QR_code
- https://github.com/Midbin/cades

**Comment by ndsboy** [comment]
fixed with https://github.com/swablab/documents/commit/a16ceaa82e68cee88b30b36c8b4869ec05a6fbd8
